version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: beevelop/ionic
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: ionic build
          command: ionic cordova build browser --prod
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: firebase deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
