version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - run:
          name: ionic build
          command: ionic cordova build browser --prod
      - run:
          name: firebase deploy
          command: firebase deploy
